name = "hello-cf-rs"
main = "build/worker/shim.mjs"
compatibility_date = "2024-09-28"

[[kv_namespaces]]
binding = "cities"
id = "c56e4e0d1874436fa1375d1d07702034"

[build]
command = "cargo install -q worker-build && worker-build --release"

